apiVersion: v1
data:
  maxmemory: 2Mi
  maxmemory-policy: allkeys-lru
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-10T14:07:02Z"
  name: redis-config
  namespace: default
  resourceVersion: "27619"
  uid: e41d88b9-4098-4c53-bf52-a26728f8039c
